name: Pylint and Pytest

on: [push]

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=7 $(git ls-files '*.py')
  pytest:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environtment variables and run test file
        run: |
          export CLIENT_ID="${{secrets.CLIENT_ID}}"
          export CLIENT_SECRET="${{secrets.CLIENT_SECRET}}"
          export OAUTH_CONNECT_URI="${{secrets.OAUTH_CONNECT_URI}}"
          export PRODUCT_URI="${{secrets.PRODUCT_URI}}"
          export LOCATION_URI="${{secrets.LOCATION_URI}}"
          python test_controllers.py
